[workspace]
resolver = "2"
members = ["crates/qvp-format", "crates/qvp-convert", "crates/qvp-core", "crates/qvp-ffi"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/quran-ws/quran-engine"
homepage = "https://quran.ws/blocks/quran-engine"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
