#!/usr/bin/env python3
"""Regenerate the `is_mark` ranges in crates/qvp-core/src/text.rs.

The shared search-fold spec defines a mark by Unicode general category
(Mn Me Lm Sk So Cf). qvp-core has no dependencies and will not carry a Unicode
category table, so the Arabic-relevant subset is written out as ranges. This
script rewrites the block between the `// generated by scripts/gen-mark-table.py`
markers in `is_mark`; `--check` exits 1 if the file is out of date (CI runs it).
"""
import re
import sys
import unicodedata
from pathlib import Path

TEXT_RS = Path(__file__).resolve().parent.parent / "crates/qvp-core/src/text.rs"
BEGIN = "        // generated by scripts/gen-mark-table.py: begin\n"
END = "        // generated by scripts/gen-mark-table.py: end\n"

CATEGORIES = {"Mn", "Me", "Lm", "Sk", "So", "Cf"}
SPANS = [(0x0600, 0x06FF), (0x0750, 0x077F), (0x08A0, 0x08FF), (0xFB50, 0xFDFF),
         (0xFE70, 0xFEFF), (0x200B, 0x200F), (0x2060, 0x2064), (0x10E60, 0x10E7E)]

points = {c for a, b in SPANS for c in range(a, b + 1)
          if unicodedata.category(chr(c)) in CATEGORIES}

ranges, start, prev = [], None, None
for c in sorted(points):
    if start is None:
        start = prev = c
    elif c == prev + 1:
        prev = c
    else:
        ranges.append((start, prev))
        start = prev = c
ranges.append((start, prev))

terms = [f"0x{a:04X}..=0x{b:04X}" if a != b else f"0x{a:04X}" for a, b in ranges]
lines = [f"        // {len(points)} codepoints, {len(ranges)} ranges"]
line = ""
for i, t in enumerate(terms):
    piece = t + (" | " if i < len(terms) - 1 else "")
    if len(line) + len(piece) > 92:
        lines.append("        " + line.rstrip())
        line = ""
    line += piece
lines.append("        " + line.rstrip())
block = BEGIN + "\n".join(lines) + "\n" + END

src = TEXT_RS.read_text()
pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
if not pattern.search(src):
    sys.exit(f"{TEXT_RS}: markers not found")
new = pattern.sub(lambda _: block, src)
if "--check" in sys.argv:
    if new != src:
        sys.exit(f"{TEXT_RS} is out of date: run scripts/gen-mark-table.py")
    print("is_mark ranges are up to date")
elif new != src:
    TEXT_RS.write_text(new)
    print(f"rewrote is_mark ranges in {TEXT_RS}")
else:
    print("is_mark ranges already up to date")
