import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { decodeGeometry } from './lite.mjs'

// Generated by qvp-format::encode from a synthetic page. It covers direct and
// instanced paths and every QVP curve operation without bundling Mushaf data.
const hex = (await readFile(new URL('../conformance/qvp1-lite.hex', import.meta.url), 'utf8')).trim()
const bytes = Uint8Array.from(hex.match(/../g), byte => Number.parseInt(byte, 16))
const page = decodeGeometry(bytes)

assert.deepEqual([page.number, page.width, page.height], [7, 345, 550])
assert.deepEqual(page.paths.map(path => [...path.ops]), [
  [0, 1, 2, 3, 4],
  [0, 1, 1, 4]
])
assert.deepEqual(page.paths.map(path => [...path.pts]), [
  [1, 2, 3, 2, 3.5, 2.5, 3, 3, 2.5, 3.5, 1.5, 3.5, 1, 3],
  [5, 6, 7, 6, 7, 8]
])
assert.deepEqual(page.paths.map(path => path.rule), ['evenodd', 'nonzero'])
assert.deepEqual(page.words, [
  [1, 2, 3.5, 3.5],
  [5, 6, 7, 8]
])

assert.throws(() => decodeGeometry(bytes.subarray(0, -1)), /section length/)
const wrongMagic = bytes.slice()
wrongMagic[0] = 0
assert.throws(() => decodeGeometry(wrongMagic), /Expected a QVP1 page/)

console.log('ok  lite decoder matches the QVP1 conformance fixture')
