import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { decodeGeometry, QvpLitePage } from './lite.mjs'

// Generated by qvp-format::encode from a synthetic page. It covers direct and
// instanced paths and every QVP curve operation without bundling Mushaf data.
const hex = (await readFile(new URL('../conformance/qvp1-lite.hex', import.meta.url), 'utf8')).trim()
const bytes = Uint8Array.from(hex.match(/../g), byte => Number.parseInt(byte, 16))
const page = decodeGeometry(bytes)

assert.deepEqual([page.number, page.width, page.height], [7, 345, 550])
assert.deepEqual(page.paths.map(path => [...path.ops]), [
  [0, 1, 2, 3, 4],
  [0, 1, 1, 4]
])
assert.deepEqual(page.paths.map(path => [...path.pts]), [
  [1, 2, 3, 2, 3.5, 2.5, 3, 3, 2.5, 3.5, 1.5, 3.5, 1, 3],
  [5, 6, 7, 6, 7, 8]
])
assert.deepEqual(page.paths.map(path => path.rule), ['evenodd', 'nonzero'])
assert.deepEqual(page.words, [
  { index: 0, surah: 2, ayah: 3, word: 1, lineIndex: 0, ayahIndex: 0, firstPath: 0, nPaths: 1, box: [1, 2, 3.5, 3.5] },
  { index: 1, surah: 2, ayah: 3, word: 2, lineIndex: 0, ayahIndex: 0, firstPath: 1, nPaths: 1, box: [5, 6, 7, 8] }
])
const interactivePage = Object.assign(Object.create(QvpLitePage.prototype), { words: page.words })
assert.equal(interactivePage.hitTest(2, 3), page.words[0])
assert.equal(interactivePage.hitTest(6, 7), page.words[1])
assert.equal(interactivePage.hitTest(4, 4), null)

let nextPath = 0
globalThis.Path2D = class {
  constructor() { this.id = nextPath++ }
  moveTo() {}
  lineTo() {}
  quadraticCurveTo() {}
  bezierCurveTo() {}
  closePath() {}
}
const renderedPage = new QvpLitePage({
  width: 10,
  height: 20,
  number: 1,
  paths: [
    { ops: [0], pts: [1, 1], rule: 'evenodd' },
    { ops: [0], pts: [2, 2], rule: 'nonzero' },
    { ops: [0], pts: [3, 3], rule: 'nonzero' }
  ],
  words: [
    { firstPath: 0, nPaths: 1 },
    { firstPath: 2, nPaths: 1 }
  ]
})
const calls = []
const ctx = {
  save: () => calls.push(['save']),
  setTransform: (...args) => calls.push(['setTransform', ...args]),
  set fillStyle(value) { calls.push(['fillStyle', value]) },
  fill: (path, rule) => calls.push(['fill', path.id, rule]),
  restore: () => calls.push(['restore'])
}
renderedPage.drawWords(ctx, [1, 0, 1], { scale: 2, x: 3, y: 4, ink: 'red' })
renderedPage.drawDecorations(ctx, { scale: 5, x: 6, y: 7, ink: 'blue' })
assert.deepEqual(calls, [
  ['save'],
  ['setTransform', 2, 0, 0, 2, 3, 4],
  ['fillStyle', 'red'],
  ['fill', 2, 'nonzero'],
  ['fill', 0, 'evenodd'],
  ['restore'],
  ['save'],
  ['setTransform', 5, 0, 0, 5, 6, 7],
  ['fillStyle', 'blue'],
  ['fill', 1, 'nonzero'],
  ['restore']
])
assert.throws(() => renderedPage.drawWords(ctx, [2]), RangeError)
assert.equal('paths' in renderedPage, false)

assert.throws(() => decodeGeometry(bytes.subarray(0, -1)), /section length/)
const wrongMagic = bytes.slice()
wrongMagic[0] = 0
assert.throws(() => decodeGeometry(wrongMagic), /Expected a QVP1 page/)

console.log('ok  lite decoder matches the QVP1 conformance fixture')
